spring:
  application:
    name: invoice-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    config:
      override-none: false
      allow-override: false

server:
  port: ${SERVER_PORT:8086}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
